### ISSUE TITLE
Mockito 3 support

### ISSUE THREAD

**Issue by jaredsburrows** [mockito/mockito-kotlin#355]
Mockito was recently released - https://github.com/mockito/mockito/releases

**Comment by nhaarman** [comment]
Without having tried it, since there aren't any API changes - only java 8 is now required - it should work if you manually require 3+?

**Comment by jaredsburrows** [comment]
Based on this PR: https://github.com/jaredsburrows/android-gif-example/pull/106, we should be good. It works fine in my Robolectric tests atleast.

**Comment by azizbekian** [comment]
@nhaarman , fyi, we've had [this](https://twitter.com/_azizbekian/status/1295709126086057984) subtle issue when using mockito3 with mockito-kotlin.

**Comment by aaronweihe** [comment]
> @nhaarman , fyi, we've had [this](https://twitter.com/_azizbekian/status/1295709126086057984) subtle issue when using mockito3 with mockito-kotlin.

Mockito 3.5.12+ has byte buddy 1.10.15 so this should no longer a problem with mockito 3.

**Comment by aaronweihe** [comment]
should a 3.x branch open for mockito 3 upgrade?
