### ISSUE TITLE
Artifacts missing from JCenter

### ISSUE THREAD

**Issue by tadfisher** [mockito/mockito-kotlin#393]
It appears that artifacts for `mockito-kotlin` 2.2.0 are missing from JCenter.

- [`maven-metadata.xml`](https://jcenter.bintray.com/com/nhaarman/mockitokotlin2/mockito-kotlin/:maven-metadata.xml) lists version 2.1.0 under `<latest>`.
- The [artifact directory for 2.2.0](https://jcenter.bintray.com/com/nhaarman/mockitokotlin2/mockito-kotlin/2.2.0/) only contains the `javadoc` JAR.

**Comment by hennr** [comment]
Related to #400?

**Comment by TimvdLippe** [comment]
Yes this will be resolved as part of #400. Therefore, I am closing this issue as duplicate of #400
