### ISSUE TITLE
Migrate release process to Shipkit

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito-kotlin#400]
Similar to `mockito-core` and `mockito-scala`, let's migrate the release process to Shipkit. The Maven Central artifact location should become https://repo1.maven.org/maven2/org/mockito/mockito-kotlin/

**Comment by mockitoguy** [comment]
Sure!

**Comment by TimvdLippe** [comment]
@mockitoguy I would like to finish this task at the end of this week, so that we can prepare the announcements for the artifact move and do some general cleanups. Would it be possible if you could get us a release on Maven Central by this week or is that too ambitious?

**Comment by mockitoguy** [comment]
I'll put some cycles into it this week. Let's see how it goes. Thanks!

**Comment by mockitoguy** [comment]
I'm making progress in this branch: https://github.com/mockito/mockito-kotlin/tree/sf Thanks for patience!

**Comment by TimvdLippe** [comment]
Fixed 🎉

**Comment by hennr** [comment]
It's not on mvn central yet though, is it?

**Comment by TimvdLippe** [comment]
It's published at https://repo1.maven.org/maven2/org/mockito/kotlin/mockito-kotlin/

**Comment by hennr** [comment]
Yep, does as well for me now. Nice!

Let's see if search.maven.org finds it as well tomorrow.

**Comment by hennr** [comment]
I just included the new artifact in our project, works fine!
