### ISSUE TITLE
Only publish to Maven Central for functional changes

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito-kotlin#418]
https://github.com/mockito/mockito-kotlin/commit/bcbea6a9c9689742e82c9c511ad1cb06fcdf842f was published to Maven Central (https://github.com/mockito/mockito-kotlin/runs/2174606136#step:4:185) but made no functional changes. To avoid spamming the Maven Central directory, we should only publish new versions that contain meaningful changes.

**Comment by mockitoguy** [comment]
Sounds good. I started iterating on this (some progress here: #421)
