### ISSUE TITLE
Verification of suspend functions?

### ISSUE THREAD

**Issue by alwa** [mockito/mockito-kotlin#431]
I've read the wiki and there is no example how to verify that a suspend function has been called.

Is this implemented?

In Mockk the equivalent is called "coVerify()", see: https://mockk.io/

**Comment by bohsen** [comment]
It's just verify with `mockito-kotlin`:

```kt
@Test
 fun verifySuspendFunctionCalled() {
     /* Given */
    val m = mock<SomeInterface>()

    /* When */
    runBlocking { m.suspending() }

    /* Then */
    runBlocking { verify(m).suspending() }
}
```

[Take a look at the tests](https://github.com/mockito/mockito-kotlin/blob/30bb37958bd8ab408b5ba751f6fee794fe54be06/mockito-kotlin/src/test/kotlin/test/CoroutinesTest.kt#L115).

**Comment by TimvdLippe** [comment]
Closing per the above. Thanks for the explanation @bohsen !
