### ISSUE TITLE
Remove verifyZeroInteractions?

### ISSUE THREAD

**Issue by rashadsookram** [mockito/mockito-kotlin#446]
I was trying to update to Mockito 4, and I noticed that I was getting `NoSuchMethodError`s when using Mockito-Kotlin's [`verifyZeroInteractions`](https://github.com/mockito/mockito-kotlin/blob/3.2.0/mockito-kotlin/src/main/kotlin/org/mockito/kotlin/Verification.kt#L84-L91).

After looking into it, it turns out that this was happening because `Mockito.verifyZeroInteractions` was [removed as of Mockito 4](https://github.com/mockito/mockito/pull/2418), and Mockito-Kotlin hasn't been updated to build against Mockito 4 yet. I also noticed that `verifyZeroInteractions` has been [marked as deprecated](https://github.com/mockito/mockito-kotlin/pull/401) in Mockito-Kotlin, but there hasn't been a new release since then.

If there are plans of releasing a Mockito-Kotlin 4 soon, maybe `verifyZeroInteractions` can be removed? Or if there's going to be another update for 3.x first, maybe the implementation of `verifyZeroInteractions` can be changed to call through to `verifyNoMoreInteractions` instead, so that it's usable (but still deprecated) with Mockito 4?

**Comment by TimvdLippe** [comment]
Ah yes, we should remove it from `mockito-kotlin` as well. Do you mind sending us a PR?
