### ISSUE TITLE
Mocktio kotlin versioning

### ISSUE THREAD

**Issue by emartynov** [mockito/mockito-kotlin#451]
I understood that it will be linked to the mockito releases. Was I wrong?

**Comment by TimvdLippe** [comment]
Mockito-kotlin is versioned by SEMVER (https://github.com/mockito/mockito-kotlin#versioning), but independent of `mockito-core`, as we treat as a standalone project. However, whenever we would bump the required version of `mockito-core` which would include a major bump, we would do a major bump for `mockito-kotlin` as well. E.g. `mockito-kotlin` will likely receive as many, but maybe more major releases than `mockito-core`.
