### ISSUE TITLE
Version 4.1.0 not plublished to Maven

### ISSUE THREAD

**Issue by fmestrone** [mockito/mockito-kotlin#462]
Hi all,

I can see a version 4.1.0 here on Github, but it is not present in Maven central. Is there any reason for this?

Thanks

**Comment by TimvdLippe** [comment]
I think the auto-releasing machinery didn't run correctly. We can delete the tag when we want to release again.

**Comment by MartinX3** [comment]
Still a problem.

**Comment by TimvdLippe** [comment]
I attempted to fix this in #466 but it seems like we also need a newer version of Shipkit so that it doesn't crash when a tag already exists:

```
    * underlying problem: POST https://api.github.com/repos/mockito/mockito-kotlin/releases failed, response code = 422, response body:
  {"message":"Validation Failed","errors":[{"resource":"Release","code":"already_exists","field":"tag_name"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-release"}
    * troubleshooting: please run Gradle with '-s' to see the full stack trace or inspect the build scan
    * thank you for using Shipkit!
```
https://github.com/mockito/mockito-kotlin/actions/runs/3533349690/jobs/5928896985

**Comment by MartinX3** [comment]
Thank you very much for your fast response. :)

**Comment by JayExtra** [comment]
Still having this problem. Any success on deploying the fix?

**Comment by TimvdLippe** [comment]
We need to bump our version of Shipkit before we can create releases via GitHub tags. #468 should fix that.

**Comment by TimvdLippe** [comment]
4.1.0 has been released to Maven Central: https://repo1.maven.org/maven2/org/mockito/kotlin/mockito-kotlin/4.1.0/
