### ISSUE TITLE
any() method is not compatible with mockito one

### ISSUE THREAD

**Issue by konrad-poczatek** [mockito/mockito-kotlin#465]
Hi!

In mockito any() method: `Matches <strong>anything</strong>, including nulls and varargs.`
In mockito-kotlin any() method: `Matches any object, excluding nulls.`

Is it done on purpose?

**Comment by FyiurAmron** [comment]
@konrad-poczatek yes, it's by design:

https://github.com/mockito/mockito-kotlin/wiki

>Mockito returns null values for calls to method like any(), which can cause IllegalStateException when passing them to non-nullable parameters. This library solves that issue by trying to create actual instances to return.

**Comment by konrad-poczatek** [comment]
@FyiurAmron thank you very much. There is just few words in Wiki and I didn't read them. Shame on me.
