### ISSUE TITLE
`org.mockito.kotlin.verifyNoInteractions` alias is missing from the 3.x branch

### ISSUE THREAD

**Issue by ZakTaccardi** [mockito/mockito-kotlin#469]
https://github.com/mockito/mockito-kotlin/pull/401 was not merged into `3.x` of `mockito-kotlin` - it is missing in `mockito-kotlin:3.2.0` while `org.mockito.Mockito.verifyNoInteractions` exists in `mockito-core`.

Releasing a `3.2.1` version of `mockito-kotlin` with this would be very appreciated (to make migrating to `4.x` easier)!

**Comment by TimvdLippe** [comment]
We do not backmerge such changes to older releases. Please use the latest version.
