### ISSUE TITLE
Should mockito kotlin have transitive dependency to mockito inline?

### ISSUE THREAD

**Issue by emartynov** [mockito/mockito-kotlin#475]
Classes by default are closed for extension in Kotlin. 
For mocking final classes, we have to use mockito inline.
So should mockito kotlin have transitive dependency to the kotlin inline?

**Comment by emartynov** [comment]
This would also make a hard reference to all possible changes in the core mockito.

**Comment by TimvdLippe** [comment]
`mockito-core` now uses the inline mockmaker by default per Mockito 5: https://github.com/mockito/mockito/releases/tag/v5.0.0

**Comment by emartynov** [comment]
@TimvdLippe will mockito kotlin get a new release soon?

**Comment by TimvdLippe** [comment]
@emartynov if you want to send us a PR that bumps Mockito and makes the CI pass, sure I can publish a new release.

**Comment by emartynov** [comment]
I'm afraid, except for the version bump, there should be addressed #473 . I will check if I can write a variant of the mock function that covers this situation.

**Comment by emartynov** [comment]
Ah sorry, I meant #474

**Comment by elomonaco** [comment]
having this support Mockito 5 would be amazing :)
