### ISSUE TITLE
Mockito 5.1 support

### ISSUE THREAD

**Issue by elomonaco** [mockito/mockito-kotlin#478]
Mockito is now on version 5.1 and it appears the kotlin version is still on Mockito 4.1. Is there any plans to get in sync with the main Mockito library?

Mockito 5.1 has a few things I'd like to use but this is a blocker.

**Comment by TimvdLippe** [comment]
I would be happy to merge a PR that bumps the version of `mockito-core`

**Comment by lukas-krecan** [comment]
[This](https://github.com/mockito/mockito-kotlin/pull/482) may be a good start.
