### ISSUE TITLE
Add mockito-kotlin inside mockito-bom

### ISSUE THREAD

**Issue by BraisGabin** [mockito/mockito-kotlin#484]
It would be nice to be able to use the current `mockito-bom` to define the version of `mockito-kotlin`. I know that, right now, their versions are not fully aligned but it would be really nice.

**Comment by TimvdLippe** [comment]
I understand the request and if they follow the same versioning cycle, this makes a lot of sense. However, since they publish at different times and are therefore not considered part of the same bundle (just like `mockito-scala`), I don't think we should do so.
