### ISSUE TITLE
mockito-kotlin upgrade from 4.1.0 to 5.1.0 fails with latest Kotlin

### ISSUE THREAD

**Issue by pwihmag** [mockito/mockito-kotlin#494]
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

//run
mvn versions:update-properties

//before 

<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>1.9.20-Beta2</kotlin.version>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlinx-coroutines.version>1.7.3</kotlinx-coroutines.version>
        <junit.version>4.13.2</junit.version>
        <mockito-kotlin.version>4.1.0</mockito-kotlin.version>
        <mockito-inline.version>4.10.0</mockito-inline.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <guice.version>7.0.0</guice.version>
        <maven-assembly-plugin.version>3.6.0</maven-assembly-plugin.version>
        <maven-surefire-plugin.version>3.1.2</maven-surefire-plugin.version>
    </properties>

//after
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>1.9.20-Beta2</kotlin.version>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlinx-coroutines.version>1.7.3</kotlinx-coroutines.version>
        <junit.version>4.13.2</junit.version>
        <mockito-kotlin.version>5.1.0</mockito-kotlin.version>
        <mockito-inline.version>5.2.0</mockito-inline.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <guice.version>7.0.0</guice.version>
        <maven-assembly-plugin.version>3.6.0</maven-assembly-plugin.version>
        <maven-surefire-plugin.version>3.1.2</maven-surefire-plugin.version>
    </properties>

//error in mvn clean install
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

**Comment by pwihmag** [comment]
//The before section was - dont know why it disappered
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>1.9.20-Beta2</kotlin.version>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlinx-coroutines.version>1.7.3</kotlinx-coroutines.version>
        <junit.version>4.13.2</junit.version>
        <mockito-kotlin.version>4.1.0</mockito-kotlin.version>
        <mockito-inline.version>4.10.0</mockito-inline.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <guice.version>7.0.0</guice.version>
        <maven-assembly-plugin.version>3.6.0</maven-assembly-plugin.version>
        <maven-surefire-plugin.version>3.1.2</maven-surefire-plugin.version>
    </properties>

**Comment by TimvdLippe** [comment]
Mockito 5 no longer supports Java 8: https://github.com/mockito/mockito/releases/tag/v5.0.0
