### ISSUE TITLE
Release is broken

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/mockito-kotlin#509]
```
* What went wrong:
Execution failed for task ':initializeSonatypeStagingRepository'.
> Failed to find staging profile for package group: 
```

https://github.com/mockito/mockito-kotlin/actions/runs/7603042146/job/20704315982

We are also facing release issues on `mockito-core` (https://github.com/mockito/mockito/issues/3235) so we should probably audit all of our Mockito artifact release pipelines.

**Comment by TWiStErRob** [comment]
@TimvdLippe raised PR https://github.com/mockito/mockito-kotlin/pull/514

**Comment by TimvdLippe** [comment]
Amazing work @TWiStErRob ! https://repo1.maven.org/maven2/org/mockito/kotlin/mockito-kotlin/5.3.1/ has been released 🎉

**Comment by TWiStErRob** [comment]
Haha, thanks, but I broke it in the first place 🫣. Feel free to tag me if you suspect I caused something or might know the answer/solution.

@TimvdLippe you might want to hand-edit [5.3.0 in GH releases](https://github.com/mockito/mockito-kotlin/releases/tag/5.3.0) to note that there are no artifacts for that.
